config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "goods#index"
  resources :goods
  get '/users/:username/profile', to: 'users#profile', as: :user_profile
  match "/users/:username/edit_profile" => "users#edit_profile", as: :edit_user_profile, via: [:get, :post]
  match '/users/goods_list' => "users#goods_list", as: :user_goods_list, via: [:get]
  match '/users/goods_list' => "users#delete_good", as: :user_delete_good, via: [:delete]
  root :to => redirect('/goods')

  get '/:id/delete', to:'goods#delete', as: 'delete_good'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/goods.rb
class Goods < ActiveRecord::Base
  geocoded_by :address
  after_validation :geocode

  def self.all_goods
    Goods.where.not(name: nil, latitude: nil, longitude: nil)
  end

  def self.explore_goods(lat, long, sort)
    goods = Goods.where.not(name: nil, latitude: nil, longitude: nil).order(sort)
    explore = {
      'goods': []
    }
    lat = lat.to_f
    long = long.to_f

    goods.each do |good|

      lats = []
      longs = []
      if !good.latitude.nil? && !good.longitude.nil?
        lats.append(good.latitude)
        longs.append(good.longitude)
      end
      if !good.latitude1.nil? && !good.longitude1.nil?
        lats.append(good.latitude1)
        longs.append(good.longitude1)
      end
      if !good.latitude2.nil? && !good.longitude2.nil?
        lats.append(good.latitude2)
        longs.append(good.longitude2)
      end

      (0..lats.length-1).each do |i|
        lat_diff = (lat - lats[i]) * 3.1415926 / 180.0
        lng_diff = (long - longs[i]) * 3.1415926 / 180.0
        lat_sin = Math.sin(lat_diff / 2.0) ** 2
        lng_sin = Math.sin(lng_diff / 2.0) ** 2
        first = Math.sqrt(lat_sin + Math.cos(lat * 3.1415926 / 180.0) * Math.cos(lats[i] * 3.1415926 / 180.0) * lng_sin)
        result = Math.asin(first) * 2 * 6378137.0

        next unless result.to_i < 1000

        unless explore.key?(good.id)
          explore[good.id] = {
            'lats': [],
            'longs': []
          }
          explore[:goods].append(good)
        end
        # puts explore
        explore[good.id][:lats].append(lats[i])
        explore[good.id][:longs].append(longs[i])

      end
    end

    explore
  end
end


app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def self.get_user_by_username(username)
    User.find_by(username: username)
  end

  def self.get_goods_of_user(username)
    Goods.where(user_name: username).to_a
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :address])
  end
end

app/controllers/goods_controller.rb
# frozen_string_literal: true

class GoodsController < ApplicationController
  before_action :find_good, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[new create delete update destroy]

  def index
    on_home_page = params[:clear] == 'clear' || !params[:sort].nil?
    explore_mode = !params[:latitude].nil? && !params[:longitude].nil?
    sort = on_home_page ? params[:sort] : session[:sort]
    if session[:sort] != params[:sort] && !explore_mode
      session[:sort] = sort
      redirect_to goods_path(sort: sort)
    end

    latitude = params[:latitude]
    longitude = params[:longitude]

    if params[:sort].nil?
      @goods = Goods.all_goods
    elsif params[:sort] == 'update_time'
      @goods = Goods.all_goods.order(update_time: :desc)
    elsif params[:sort] == 'name'
      @goods = Goods.all_goods.order("lower(name)")
    end

    goods_map = nil
    if !latitude.nil? && !longitude.nil?
      goods_map = Goods.explore_goods(latitude, longitude, sort)
      @goods = goods_map[:goods]
    end

    # @hash = Gmaps4rails.build_markers(@goods) do |good, marker|
    #   marker.lat good.latitude
    #   marker.lng good.longitude
    #   marker.infowindow render_to_string(partial: "/goods/map_box", locals: { good: good })
    # end

    @hash = if !latitude.nil? && !longitude.nil?
              Gmaps4rails.build_markers(@goods) do |good, marker|
                (0..goods_map[good.id][:lats].length-1).each do |i|
                  marker.lat goods_map[good.id][:lats][i]
                  marker.lng goods_map[good.id][:longs][i]
                  marker.infowindow render_to_string(partial: "/goods/map_box", locals: { good: good })
                end
              end
            else
              Gmaps4rails.build_markers(@goods) do |good, marker|
                marker.lat good.latitude
                marker.lng good.longitude
                marker.infowindow render_to_string(partial: "/goods/map_box", locals: { good: good })
              end
            end
  end

  def show; end

  def new
    @good = Goods.new
  end

  def create
    address1 = goods_params[:address1]
    address2 = goods_params[:address2]

    goods_param = goods_params
    goods_param[:user_name] = current_user.username
    if address1 != nil
      goods_param[:latitude1], goods_param[:longitude1] = Geocoder.coordinates(address1)
    end

    if address2 != nil
      goods_param[:latitude2], goods_param[:longitude2] = Geocoder.coordinates(address2)
    end

    @good = Goods.new(goods_param)

    if @good.save
      redirect_to user_goods_list_path, notice: "#{@good.name} was successfully created."
    else
      render action: 'new'
    end
  end

  def edit
  end

  # def delete
  #   @good = Goods.find(params[:id])
  # end

  def update
    goods_param = goods_params
    if !goods_param[:address1].nil? and goods_param[:address1] != "" and goods_param[:address1] != @good.address1
      goods_param[:latitude1], goods_param[:longitude1] = Geocoder.coordinates(goods_param[:address1])
    end

    if !goods_param[:address2].nil? and goods_param[:address2] != "" and goods_param[:address2] != @good.address2
      goods_param[:latitude2], goods_param[:longitude2] = Geocoder.coordinates(goods_param[:address2])
    end

    if @good.update(goods_param)
      redirect_to user_goods_list_path, notice: 'Goods was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # def destroy
  #   if @good.destroy
  #     respond_destroy_success
  #   else
  #     respond_destroy_fail
  #   end
  # end

  private

  def find_good
    @good = Goods.find(params[:id])
  end

  def goods_params
    params.require(:goods).permit(:name, :address, :address1, :address2)
  end

  # def respond_destroy_success
  #   respond_to do |format|
  #     format.html { redirect_to goods_url }
  #     format.json { head :no_content }
  #   end
  # end
  #
  # def respond_destroy_fail
  #   respond_to do |format|
  #     format.html { redirect_to goods_url }
  #     format.json { head :forbidden }
  #   end
  # end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def profile
    @user = User.get_user_by_username(params[:username])
  end

  def goods_list
    redirect_to(root_path) unless user_signed_in?
    @goods = User.get_goods_of_user(current_user.username)
  end

  def delete_good
    @good = Goods.find_by(id: params[:id])
    @good.destroy
    redirect_to(user_goods_list_path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/views/flats/_form.html.erb
<div class="row-fluid">
  <div class="col-md-4 col-md-offset-4">
    <div class="row">

      <h1>Create/Edit your flat</h1>

      <%= form_for(@flat) do |f| %>
        <% if @flat.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@flat.errors.count, "error") %> prohibited this flat from being saved:</h2>

            <ul>
            <% @flat.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :address %>
          <%= f.text_field :address, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.submit "GO", class: "btn btn-primary" %>
        </div>
      <% end %>


    </div>
  </div>

</div>

app/views/goods/_form.html.erb
<div class="row-fluid">
  <div class="col-md-4 col-md-offset-4">
    <div class="row">

      <h1>Edit your goods</h1>

      <%= form_for(@good) do |f| %>
        <% if @good.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@good.errors.count, "error") %> prohibited this good from being saved:</h2>

            <ul>
            <% @good.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label "peferred addresses" %>
          <%= f.text_field :address, class: "form-control" %><br>
          <%= f.text_field :address1, class: "form-control" %><br>
          <%= f.text_field :address2, class: "form-control" %><br>
        </div>

        <div class="form-group">
          <%= f.submit "GO", class: "btn btn-primary" %>
        </div>
      <% end %>


    </div>
  </div>

</div>

app/views/goods/_map_box.html.erb
<div class="map_box">
  <h3><%= good.name %></h3>
  <p><%= good.address %></p>
  <% if good.address1 != "" %>
    <p><%= good.address1 %></p>
  <% end %>
  <% if good.address2 != "" %>
    <p><%= good.address2 %></p>
  <% end %>
  <%= link_to "Details", good_path(good), target: :blank, class: "btn btn-warning" %>
</div>

app/views/goods/delete.html.erb
<h1>Are you sure you want to delete it?</h1>


<%= link_to "delete", @good, method: :delete%>
<%= link_to 'Back', goods_path %>

app/views/goods/edit.html.erb
<h1>Editing goods</h1>

<%= render 'form' %>

<%= link_to 'Show', @good %> |
<%= link_to 'Back', goods_path %>

app/views/goods/index.html.erb
<div class="row-fluid">
  <div class="col-md-6">
    <div id="map" style='width: 100%; height: 600px;'></div>
  </div>
  <div class="col-md-6">
    <%# if user_signed_in? %>
    <%#= link_to new_good_path do %>
    <!--        <button class="btn btn-primary">Add new goods</button>-->
    <%# end %>
    <!--      <hr>-->
    <%# end %>

    <button class="" id="loc" onclick="explore_mode()">
      Explore Mode
    </button>

    <% if params[:latitude].nil? or params[:longitude].nil? %>
      <button class="<%= params[:sort] == "name" ? "hilite bg-warning" : "" %>">
        <%= link_to "Sort By Name", goods_path(:sort => "name"), :id => 'goods_name_header' %>
      </button>

      <button class="<%= params[:sort] == "update_time" ? "hilite bg-warning" : "" %>">
        <%= link_to "Sort By Time", goods_path(:sort => "update_time"), :id => 'update_time_header' %>
      </button>

      <button class="">
        <%= link_to "Clear Sort Status", goods_path(:clear => "clear"), :id => 'clear_order_button' %>
      </button>
    <% else %>
      <button class="">
        <%= link_to "Exit Explore Mode", goods_path, :id => 'exit_explore' %>
      </button>
    <% end %>


    <p>Search for specific items:</p>  
    <input class="form-control" id="myInput" type="text" placeholder="Item Name...">
    <br>
    <div id="ulContainer">
      <ul class="list-group" id="myList">
      <%for i in 0..@goods.length-1 do %>
        <%good = @goods[i]%>
        <li class="list-group-item" style="<%= i>3 ? "display: None" : ""%>">
          <div class="row-fluid">
            <h2><%= link_to good.name, good %></h2>
            <p><%= good.address %></p>
          </div>
        </li>
      <% end %>
      </ul>
    </div>
    <div style="text-align:center">
      <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center" id = "paginationId">
          <% for i in 1..(@goods.length/4.0).ceil do%>
            <li class="page-item" onclick="changePage(<%= i%>)"><a class="page-link" href="#"><%= i%></a></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</div>



<% content_for(:after_js) do %>
  <script type="text/javascript">
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function(){
          markers = handler.addMarkers(<%= raw @hash.to_json %>);
          handler.bounds.extendWith(markers);
          handler.fitMapToBounds();
          if (markers.length == 0) {
              handler.getMap().setZoom(2);
          } else if (markers.length == 1) {
              handler.getMap().setZoom(14);
          }
      });

      // let map, infoWindow;
      // infoWindow = new google.maps.InfoWindow();
      //
      // // const locationButton = document.createElement("button");
      // // var MyDiv =document.getElementById("loc");
      // const locationButton = document.getElementById("loc");
      // var curPos;
      //
      // locationButton.textContent = "Explore";
      // locationButton.classList.add("custom-map-control-button");
      //
      // locationButton.addEventListener("click", () => {
      //     // Try HTML5 geolocation.
      //     if (navigator.geolocation) {
      //         navigator.geolocation.getCurrentPosition(
      //             (position) => {
      //                 curPos = {
      //                     lat: position.coords.latitude,
      //                     lng: position.coords.longitude,
      //                 };
      //
      //                 // infoWindow.setPosition(pos);
      //                 // infoWindow.setContent("Location found.");
      //                 // infoWindow.open(map);
      //                 // map.setCenter(pos);
      //                 console.log(curPos)
      //             },
      //             () => {
      //                 handleLocationError(true, infoWindow, handler.getCenter());
      //             }
      //         );
      //     } else {
      //         // Browser doesn't support Geolocation
      //         handleLocationError(false, infoWindow, handler.getCenter());
      //     }
      // });

      // MyDiv.appendChild(locationButton);

      // function handleLocationError(browserHasGeolocation, infoWindow, pos) {
      //     infoWindow.setPosition(pos);
      //     infoWindow.setContent(
      //         browserHasGeolocation
      //             ? "Error: The Geolocation service failed."
      //             : "Error: Your browser doesn't support geolocation."
      //     );
      //     // infoWindow.open(map);
      // }


  </script>

  <script>
      function explore_mode() {
          let curPos;

          if (navigator.geolocation) {
              navigator.geolocation.getCurrentPosition(
                  (position) => {
                      curPos = {
                          lat: position.coords.latitude,
                          lng: position.coords.longitude,
                      };
                      console.log(curPos)
                      window.location.href = '/goods?latitude=' + curPos.lat + '&longitude=' + curPos.lng
                  }
              );
          }
      }
  </script>


  <script>
    
    $(document).ready(function(){
      $("#myInput").on("keyup", function() {                  

        var value = $(this).val().toLowerCase();

        $('#myList').empty()

        <%for i in 0..@goods.length-1 do %>
          <%good = @goods[i]%>
          var node_a = document.createElement('a')
          node_a.href = "/goods/<%= good.id%>"
          node_a.innerHTML = "<%=good.name%>"

          var node_h2 = document.createElement('h2')
          node_h2.appendChild(node_a)

          var node_p = document.createElement('p')
          node_p.innerHTML = "<%=good.address%>"

          var node_div = document.createElement('div')
          node_div.classList.add("row-fluid")
          node_div.appendChild(node_h2)
          node_div.appendChild(node_p)

          var node_li = document.createElement('li')
          node_li.classList.add("list-group-item")
          node_li.appendChild(node_div)

          document.getElementById("myList").appendChild(node_li)
        <% end %>

        $('#myList').children().each(function () {
            $(this).show();
        });


        $('#myList').children().each(function () {
            if ($(this).find('h2:first').text().toLowerCase().indexOf(value) <= -1) {
              $(this).remove();
            }
        });

        let lst = document.getElementById("myList")

        for(var i=0, len = lst.childElementCount ; i < len; ++i){
            if (i<4) {
              lst.children[i].style.display = null
            } else {
              lst.children[i].style.display = "none"
            }
        }

        $('#paginationId').empty()
        

        let pag = document.getElementById("paginationId")
        for(var i=0; i<Math.ceil(lst.childElementCount/4.0); ++i) {
            var node_a = document.createElement('a')
            node_a.classList.add("page-link")
            node_a.href = "#"
            node_a.innerHTML = (i+1).toString()
            var node_li = document.createElement('li')
            node_li.classList.add("page-item")
            node_li.setAttribute("onclick","changePage("+(i+1).toString()+")");
            node_li.appendChild(node_a)
            pag.appendChild(node_li)
        }
      });
    });
  </script>  
<% end %>


<script>
    function changePage(page) {
      let lst = document.getElementById("myList")

      var children = lst.children;
      for (var i = 0; i < children.length; i++) {
        var tableChild = children[i];

        if (i >= 4*(page-1) && i <= 4*page-1) {
            tableChild.style.display = null;
        } else {
            tableChild.style.display = "none";
        }
      }
    }
</script>

app/views/goods/new.html.erb
<div class="row-fluid">
  <div class="col-md-4 col-md-offset-4">
    <div class="row">

      <h1>Create your goods</h1>

      <%= form_for @good, :url => { :action => :create } do |f| %>
        <% if @good.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@good.errors.count, "error") %> prohibited this good from being saved:</h2>

            <ul>
            <% @good.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control" %>
        </div>

        <div class="form-group">
          <label for="good_address">Address 1</label>
          <input id='gmaps_input_address' placeholder='Start typing a place name...' type='text' class="form-control" name="goods[address]"/>
        </div>
        <div class="form-group">
          <label for="good_address_1">Address 2 [Optional]</label>
          <input id='gmaps_input_address1' placeholder='Start typing a place name...' type='text' class="form-control" name="goods[address1]"/>
        </div>
        <div class="form-group">
          <label for="good_address_2">Address 3 [Optional]</label>
          <input id='gmaps_input_address2' placeholder='Start typing a place name...' type='text' class="form-control" name="goods[address2]"/>
        </div>
        <div class="form-group">
          <%= f.submit "GO", class: "btn btn-primary" %>
        </div>
      <% end %>

      <%= link_to "get batck to list", goods_path %>


    </div>
  </div>

</div>

app/views/goods/show.html.erb
<div class="row-fluid">
  <div class="col-md-8 col-md-offset-2">
    <div class="row">
      <h2><%= @good.name %></h2>
      <p><%= @good.address %></p>
      <p><%= @good.description %></p>
      <br>
      <p>preferred locations</p>
      <ul>
        <li><%= @good.address %></li>
        <% if @good.address1 != "" %>
        <li><%= @good.address1 %></li>
        <% end %>
        <% if @good.address2 != "" %>
          <li><%= @good.address2 %></li>
        <% end %>
      </ul>

      <p><%= link_to "Seller: #{@good.user_name}", user_profile_path(@good.user_name) %></p>

      <%= link_to "Back", goods_path %>
    </div>

    <hr>

<!--    <div class="row">-->
      <%#= image_tag "https://maps.googleapis.com/maps/api/staticmap?key=AIzaSyACX632gUDpJlGXU0pXVCLE7gRWvWiL6UU&center=#{@good.latitude},#{@good.longitude}&zoom=14&size=640x400&markers=color:black%7C#{@good.latitude},#{@good.longitude}" %>
<!--    </div>-->

  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NearBuy</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= csrf_meta_tags %>
  <%= render "navbar/navbar" %>
  <br/>
</head>
<body>

<div class="container-fluid">
  <%= yield %>
</div>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyACX632gUDpJlGXU0pXVCLE7gRWvWiL6UU&libraries=places">
</script>
<script src='//cdn.jsdelivr.net/gmaps4rails/2.1.2/gmaps4rails.js'> </script>
<script src='//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore.js'> </script>
<%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
<%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>
<!--<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>-->
<!--<script type="text/javascript" src="https://raw.github.com/HPNeo/gmaps/master/gmaps.js"></script>-->


<!--<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyACX632gUDpJlGXU0pXVCLE7gRWvWiL6UU&callback=initMap"></script>-->
<!--        type="text/javascript"></script>-->
<!--<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>-->
<!--<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"></script>-->
<%= javascript_include_tag "application" %>

<%= yield(:after_js) %>
</body>
</html>

app/views/navbar/_navbar.html.erb
<div class="collapse navbar-collapse bg-warning" id = "main-nav-collapse" >
  <a class="navbar-brand">NearBuy</a>
  <div class="nav navbar-nav navbar-left">
    <%= link_to "Home", goods_path, class:"nav-link btn btn-primary navbar-btn" %>
  </div>
  <div class="nav navbar-nav navbar-right" style="padding-right: 10px">
    <% if user_signed_in? %>
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link btn btn-primary navbar-btn" %>
      <%= link_to "Profile", user_profile_path(:username => current_user.username), class:"nav-link btn btn-primary navbar-btn" %>
      <%= link_to "Goods List", user_goods_list_path(), class:"nav-link btn btn-primary navbar-btn" %>
    <% else %>
      <%= link_to "Sign Up", new_user_registration_path, class:"nav-link btn btn-primary navbar-btn" %>
      <%= link_to "Sign In", new_user_session_path, class:"nav-link btn btn-primary navbar-btn" %>
    <% end %>
  </div>
</div> <!-- /.navbar-collapse -->

app/views/navbar/navbar.html.erb
<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand">NearBuy</a>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="https://mysterious-oasis-25704.herokuapp.com/">Home</a>
        </li>
      </ul>
      <div class="d-flex">
        <% if user_signed_in? %>
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
          <%= link_to "Profile", user_profile_path(:username => current_user.username), class:"nav-link" %>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
          <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/users/goods_list.html.erb
<div class="row-fluid">
    <div class="col-md-6">
        <% if user_signed_in? %>
        <%= link_to new_good_path do %>
        <button class="btn btn-primary">Add new goods</button>
        <% end %>
        <hr>
        <% end %>

        <ul class="list-group" id="myList">

            <% @goods.each do |good| %>
            <li class="list-group-item">
                <div class="row-fluid">
                    <h2><%= link_to good.name, good %></h2>
                    <p><%= good.address %></p>
                  <%= link_to "Edit", edit_good_path(good), class: "btn btn-default"  %>
                  <%= link_to "Delete", user_delete_good_path(id: good.id), class: "btn btn-default", method: :delete  %>
                </div>
            </li>
            <% end %>
        </ul>

    </div>
</div>

app/views/users/profile.html.erb
<div class="card text-center" style="border-style: dotted; border-width: thick">
  <div class="card-header">
    <h1><%= @user.username %></h1>
  </div>
  <div class="card-body">
    <h2 class="card-title"><%= @user.email %></h2>
    <%= link_to "Goods List", user_goods_list_path(), class:"nav-link btn btn-primary navbar-btn" %>
  </div>
  <br/>
  <div class="card-footer text-muted">
    <%= link_to 'Back to', goods_path %> @NearBuy 
  </div>
  
</div>